export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const SEARCH_VIDEOGAMES = 'SEARCH_VIDEOGAMES';
export const GET_GAME_BYID = 'GET_GAME_BYID';
export const GET_GENRES = 'GET_GENRES';
export const ORDER_GAMES = 'ORDER_GAMES';
export const ORDER_BY_GENRE = 'ORDER_BY_GENRE';
